[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.ols]
command = "ols"

[[language]]
name = "odin"
scope = "source.odin"
injection-regex = "odin"
file-types = ["odin"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
language-servers = ["ols"]
auto-format = true
formatter = { command = "odinfmt" }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
